config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("versutus.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

# Tangle URLS

urlpatterns += [
    path("tangle/", include("versutus.tangle.urls", namespace="tangle")),
    path("community/", include("versutus.community.urls", namespace="community")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

versutus/tangle/urls.py
from django.urls import path

from versutus.tangle.views import (
    crew3_tools_view,
    iota,
    shimmer,
    smr_address_view,
    tools_view,
)

app_name = "tangle"

urlpatterns = [
    path("iota/", view=iota, name="iota"),
    path("shimmer/", view=shimmer, name="shimmer"),
    path("tools/", view=tools_view, name="tools"),
    path("tools/crew3_smr/", view=crew3_tools_view, name="crew3_tools"),
    path("tools/smr_address/", view=smr_address_view, name="smr_address"),
]

versutus/tangle/models.py
from django.db import models

# Create your models here.


class DiscordUser(models.Model):
    user_id = models.BigIntegerField(primary_key=True)
    user_name = models.CharField(max_length=255)
    shimmer_address_mainnet = models.CharField(max_length=63)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class DiscordGuild(models.Model):
    guild_id = models.BigIntegerField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class DiscordUserConnections(models.Model):
    connection_type = models.CharField(max_length=255)
    connection_username = models.CharField(max_length=255)
    connection_verified = models.BooleanField()
    connection_visibility = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        DiscordUser, on_delete=models.CASCADE, related_name="connections"
    )


class NftCampaign(models.Model):
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="nft_campaigns"
    )
    nft_campaign_name = models.CharField(max_length=255)
    nft_campaign_nft_amount = models.IntegerField()
    nft_campaign_manager_name = models.CharField(max_length=255)
    nft_campaign_manager_id = models.BigIntegerField()
    nft_campaign_discord_role = models.CharField(max_length=255)
    nft_campaign_discord_role_id = models.BigIntegerField()
    nft_campaign_discord_role_eligible = models.BooleanField()
    nft_campaign_active = models.BooleanField(null=True, blank=True)
    nft_campaign_archived = models.BooleanField(null=True, blank=True)
    nft_campaign_shimmer_mainnet_address = models.CharField(max_length=63, blank=True)


class DiscordGuildRoles(models.Model):
    role_id = models.BigIntegerField(primary_key=True)
    role_name = models.CharField(max_length=255)
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="roles"
    )


class NftEligibleDiscordGuildRoles(models.Model):
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="eligible_roles"
    )
    role = models.ForeignKey(
        DiscordGuildRoles, on_delete=models.CASCADE, related_name="eligible_roles"
    )
    campaign = models.ForeignKey(
        NftCampaign, on_delete=models.CASCADE, related_name="eligible_roles"
    )


class DiscordUserSetup(models.Model):
    user = models.ForeignKey(
        DiscordUser, on_delete=models.CASCADE, related_name="setups"
    )
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="setups"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    setup_completed = models.BooleanField(default=False)


class DiscordUserRoles(models.Model):
    user = models.ForeignKey(
        DiscordUser, on_delete=models.CASCADE, related_name="roles"
    )
    role = models.ForeignKey(
        DiscordGuildRoles, on_delete=models.CASCADE, related_name="users"
    )
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="user_roles"
    )


class DiscordUserShimmerAddresses(models.Model):
    user = models.ForeignKey(
        DiscordUser, on_delete=models.CASCADE, related_name="shimmer_addresses"
    )
    shimmer_mainnet_address = models.CharField(max_length=63, blank=True)
    shimmer_devnet_address = models.CharField(max_length=63, blank=True)
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="shimmer_addresses"
    )


class NftSent(models.Model):
    user_id = models.BigIntegerField()
    guild_id = models.BigIntegerField()
    role_id = models.BigIntegerField()
    sent_at = models.DateTimeField(auto_now=True)
    campaign = models.ForeignKey(
        NftCampaign, on_delete=models.CASCADE, related_name="sent_nfts"
    )
    is_sent = models.BooleanField()


class BlacklistedUser(models.Model):
    user = models.ForeignKey(
        DiscordUser, on_delete=models.CASCADE, related_name="blacklisted_users"
    )
    guild = models.ForeignKey(
        DiscordGuild, on_delete=models.CASCADE, related_name="blacklisted_users"
    )


class IotaHexAddress(models.Model):
    address = models.CharField(max_length=64, primary_key=True)
    balance = models.BigIntegerField()


class IotaTopAddress(models.Model):
    address = models.CharField(max_length=64, primary_key=True)
    balance = models.CharField(max_length=20)


class IotaDistribution(models.Model):
    amounts = models.CharField(max_length=20)
    addresses = models.IntegerField()
    sum_balances = models.CharField(max_length=11)
    percent_addresses = models.CharField(max_length=11)
    percent_supply = models.CharField(max_length=11)


class ShimmerHexAddress(models.Model):
    address = models.CharField(max_length=80, primary_key=True)
    balance = models.BigIntegerField()


class ShimmerTopAddress(models.Model):
    address = models.CharField(max_length=80, primary_key=True)
    balance = models.CharField(max_length=20)


class ShimmerDistribution(models.Model):
    amounts = models.CharField(max_length=20)
    addresses = models.IntegerField()
    sum_balances = models.CharField(max_length=11)
    percent_addresses = models.CharField(max_length=11)
    percent_supply = models.CharField(max_length=11)


class EcosystemOpportunities(models.Model):
    thread_id = models.BigIntegerField(primary_key=True)
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=100)
    archived = models.BooleanField(default=False)
    locked = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} ({self.category})"

versutus/tangle/forms.py
from django import forms


class SmrAddressForm(forms.Form):
    address = forms.CharField(
        max_length=64,
        widget=forms.TextInput(
            attrs={"maxlength": 64, "placeholder": "Enter SMR address"}
        ),
        required=True,
    )

versutus/tangle/views.py
import csv
import logging

import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import render
from django.views.generic import TemplateView
from iota_client import (
    IotaClient as ShimmerClient,  # Imported as ShimmerClient to prevent confusion
)

from versutus.tangle.forms import SmrAddressForm
from versutus.tangle.models import (
    IotaDistribution,
    IotaTopAddress,
    ShimmerDistribution,
    ShimmerTopAddress,
)

logger = logging.getLogger(__name__)

User = get_user_model()


def is_user_in_nft_manager_group(user):
    try:
        nft_manager_group = Group.objects.get(name="NFT Managers")
    except Group.DoesNotExist:
        return False

    return nft_manager_group in user.groups.all()


def get_shimmer_richlist_from_chronicle_api(richlist_results):
    api_url = f"https://chronicle.shimmer.network/api/explorer/v2/ledger/richest-addresses?top={richlist_results}"
    response = requests.get(api_url)
    return response.json()


def iota(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    context = {
        "iota_distribution": IotaDistribution.objects.all(),
        "iota_richtlist": IotaTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
    }
    return render(request, "iota.html", context=context)


def shimmer(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    chronicle_api_richlist = get_shimmer_richlist_from_chronicle_api(richlist_results)
    for chronicle_api_entry in chronicle_api_richlist["top"]:
        shimmer_api_address = chronicle_api_entry["address"]
        shimmer_api_balance = chronicle_api_entry["balance"]
    shimmer_api_ledger_index = chronicle_api_richlist["ledgerIndex"]

    context = {
        "shimmer_distribution": ShimmerDistribution.objects.all(),
        "shimmer_richtlist": ShimmerTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
        "shimmer_api_ledger_index": shimmer_api_ledger_index,
        "shimmer_api_address": shimmer_api_address,
        "shimmer_api_balance": shimmer_api_balance,
    }
    return render(request, "shimmer.html", context=context)


def verify_content(csv_content):
    invalid_rows = []
    csv_reader = csv.reader(csv_content.splitlines())
    headers = next(csv_reader)
    if "answer" not in headers:
        invalid_rows.append((" ", "INVALID CSV FILE", " "))
        return invalid_rows

    address_index = headers.index("answer")
    if "Name" in headers:
        name_index = headers.index("Name")
    else:
        return invalid_rows
    for i, row in enumerate(csv_reader):
        logger.debug(row)
        if not verify_shimmer_address(row[address_index]):
            invalid_rows.append((row[name_index], row[address_index], i + 2))
    return invalid_rows


def verify_shimmer_address(address):
    logger.debug(f"Verifying address: {address}")
    shimmer_client = ShimmerClient()
    return shimmer_client.is_address_valid(address)


class Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "tools.html"


tools_view = Tools.as_view()


class Crew3Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "crew3_tools.html"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            csv_file = request.FILES["file"]
            csv_content = csv_file.read().decode("utf-8")
            invalid_rows = verify_content(csv_content)
            if invalid_rows:
                context = {
                    "invalid_rows": invalid_rows,
                }
                return render(request, "csv_verify.html", context=context)
            else:
                return render(request, "csv_success.html")
        return render(request, "csv_upload.html")


crew3_tools_view = Crew3Tools.as_view()


class ShimmerAddress(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "smr_address.html"
    form_class = SmrAddressForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        return self.render_to_response({"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            address = form.cleaned_data.get("address")
            if verify_shimmer_address(address):
                context = {"address": address}
                if address.startswith("rms1"):
                    context["testnet"] = True
                # Address is valid, do something
                return render(request, "smr_address_success.html", context=context)
            else:
                form.add_error("address", "Invalid address")
                context = {"address": address}
                return render(request, "smr_address_verify.html", context=context)
        return self.render_to_response({"form": form})


smr_address_view = ShimmerAddress.as_view()

versutus/tangle/templates/tools/crew3_tools.html
{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card my-4 mx-5">
                    <div class="table-responsive p-0 text-center">
                        <h5>Validate a Crew3 Export</h5>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input class="btn bg-gradient-dark" type="file" name="file">
                            <button class="btn btn-lg bg-gradient-primary btn-lg" type="submit">Upload</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

versutus/tangle/templates/tools/csv_success.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<body class="g-sidenav-show  bg-gray-200">
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <div class="alert alert-success text-white" role="alert">
            <span class="text-sm">✔️ All addresses validated successfully!</span>
          </div>
    </main>
</body>
{% endblock %}

versutus/tangle/templates/tools/csv_verify.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<body class="g-sidenav-show  bg-gray-200">
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        <div class="alert alert-danger text-white" role="alert">
            <span class="alert-link text-white">⚠️ WARNING: There are addresses with the wrong format. </span>
        </div>
        <div class="container-fluid py-4">
            <div class="row">
              <div class="col-12">
                <div class="card my-4">
                  <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                    <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                      <h6 class="text-white text-capitalize ps-3">The following lines have ⚠️ INVALID ⚠️ addresses</h6>
                    </div>
                  </div>
                  <div class="card-body px-0 pb-2">
                    <div class="table-responsive p-0">
                      <table class="table align-items-center mb-0">
                        <thead>
                          <tr>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Username</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Line number</th>
                            <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Submitted Information</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for row in invalid_rows %}
                          <tr>
                            <td>
                              <div class="d-flex px-2 py-1">
                                <div class="d-flex flex-column justify-content-center">
                                  <h6 class="text-center mb-0 text-sm">{{ row.0 }}</h6>
                                </div>
                              </div>
                            </td>
                            <td>
                                <p class="text-center text-xs font-weight-bold mb-0">{{ row.2 }}</p>
                            </td>
                            <td>
                                <p class="text-center text-xs font-weight-bold mb-0">{{ row.1 }}</p>
                            </td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
    </main>
</body>
{% endblock %}

versutus/tangle/templates/tools/smr_address.html
{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card my-4 mx-5">
                    <div class="table-responsive p-0 text-center">
                        <h5>Validate a Shimmer Mainnet address</h5>
                        <form method="post">
                            {% csrf_token %}
                            <!-- <label for="address">SMR Address:</label> -->
                            <input class="btn bg-gradient-secondary" type="text" id="address" name="address" placeholder="Enter SMR address" maxlength="64" required  style="width: 550px;">
                            <button class="btn btn-lg bg-gradient-primary btn-lg" type="submit">Validate</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

versutus/tangle/templates/tools/smr_address_success.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<body class="g-sidenav-show  bg-gray-200">
    <main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
        {% if testnet %}
        <div class="alert alert-warning alert-dismissible text-white" role="alert">
            <span class="text-sm">⚠️ The submitted address is a Shimmer TESTNET address!</span>
        </div>
        {% else %}
        <div class="alert alert-success text-white" role="alert">
            <span class="text-sm">✔️ Submitted address validated successfully!</span>
        </div>
        {% endif %}
          {{ address }}
    </main>
</body>
{% endblock %}

versutus/tangle/templates/tools/smr_address_verify.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->

{% extends "tools.html" %}

{% load i18n %}

{% block head_title %}SMR Address Tools{% endblock %}

{% block inner %}
<main class="main-content position-relative max-height-vh-100 h-100 border-radius-lg ">
    <div class="alert alert-danger text-white" role="alert">
        <span class="alert-link text-white">⚠️ WARNING: The address is wrong. </span>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card my-4">
                    <div class="table-responsive p-0">
                        <table class="table align-items-center mb-0">
                            <thead>
                            <tr>
                                <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">
                                Address
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                            <td>
                            <div class="d-flex px-2 py-1">
                                <div class="d-flex flex-column justify-content-center">
                                <h6 class="mb-0">
                                    {{ address }}
                                </h6>
                                </div>
                            </div>
                            </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

versutus/tangle/templates/tools/tools.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
<!-- Navbar -->
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
      <nav aria-label="home icon">
        <a href="{% url 'tangle:tools' %}" class="nav-link text-body font-weight-bold px-0">
          <i class="fa fa-textpattern me-sm-1"></i>
          <span class="d-sm-inline d-none">Tools</span>
        </a>
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        </div>
        <ul class="navbar-nav justify-content-end">
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'tangle:smr_address' %}" class="nav-link text-body font-weight-bold px-2">
              <span class="d-sm-inline d-none">Shimmer Mainnet Address Check</span>
            </a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'tangle:crew3_tools' %}" class="nav-link text-body font-weight-bold px-2">
              <span class="d-sm-inline d-none">Crew3 Export Adderss Check</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->
    <div class="row">
    <div class="col-md-10 offset-md-1">
        {% block inner %}
        <h1>Welcome to the tools page!</h1>
        {% endblock %}
    </div>
    </div>
{% endblock %}