config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("versutus.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

# Tangle URLS

urlpatterns += [
    path("tangle/", include("versutus.tangle.urls", namespace="tangle")),
    path("community/", include("versutus.community.urls", namespace="community")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

versutus/community/urls.py
from django.urls import path

from versutus.community.views import (
    communities_view,
    opportunities_view,
    shimmerians_view,
)

app_name = "crew3"

urlpatterns = [
    path("communities/", view=communities_view, name="communities"),
    path("communities/shimmerians/", view=shimmerians_view, name="shimmerians"),
    path("opportunities/", view=opportunities_view, name="opportunities"),
]

versutus/community/views.py
import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from versutus.tangle.models import EcosystemOpportunities

User = get_user_model()


def get_crew3_api_data(subdomain, x_api_key, page_number):
    api_url = (
        f"https://api.crew3.xyz/communities/{subdomain}/leaderboard?page={page_number}"
    )
    headers = {"x-api-key": x_api_key}
    response = requests.get(api_url, headers=headers)
    return response.json()


def opportunities_view(request):
    # Retrieve all non-archived opportunities from the database
    opportunities = EcosystemOpportunities.objects.filter(archived=False)

    # Count the number of opportunities
    count = opportunities.count()

    # Pass the opportunities and count to the template context
    context = {
        "opportunities": opportunities,
        "count": count,
    }

    return render(request, "opportunities.html", context)


@login_required
def shimmerians_view(request):
    subdomain = "shimmerians"
    x_api_key = "72812apRGCSGJsgI99NIoAzcAeF"

    # Retrieve the page number from the request query string
    page_number = int(request.GET.get("page", 1))
    users = get_crew3_api_data(subdomain, x_api_key, page_number)

    for entry in users["leaderboard"]:
        if entry.get("avatar"):
            avatar_url = entry["avatar"]
            if avatar_url.startswith("https://cdn.discordapp.com/"):
                entry["avatar"] = avatar_url
            elif avatar_url.startswith("public/"):
                entry["avatar"] = (
                    "https://crew3-production.s3.eu-west-3.amazonaws.com/public/"
                    + avatar_url[7:]
                )
            else:
                entry["avatar"] = "https://crew3.xyz" + avatar_url
    # Add the total number of users and total pages to the context dictionary
    total_users = users["totalUsers"]
    total_pages = users["totalPages"]
    context = {
        "users": users["leaderboard"],
        "total_users": total_users,
        "total_pages": total_pages,
        "current_page": page_number,
    }
    return render(request, "shimmerians.html", context=context)


class Communities(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "leaderboard.html"


communities_view = Communities.as_view()

versutus/community/templates/leaderboard.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block content %}
<a href="{% url 'community:shimmerians' %}">View Shimmerians</a>
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Shimmer token distribution</h6>
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-end opacity-7">Range</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-end opacity-7 ps-2">Addresses</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-end opacity-7 ps-2">Sum balances</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-end opacity-7 ps-2">% Addresses</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-end opacity-7 ps-2">% Supply</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for row in shimmer_distribution %}
                    <tr>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.amounts}}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.addresses }}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.sum_balances }}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.percent_addresses }}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.percent_supply }}</p>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Shimmer Richlist Top {{ richlist_results }}</h6>
              </div>
              {% if not request.user.is_authenticated %}
              <div class="alert alert-info alert-dismissible text-white" role="alert">
                <span class="text-sm">
                  <a href="{% url 'account_login' %}" class="alert-link text-white">
                    <i class="fa fa-sign-in me-sm-1"></i>
                    Login with Discord</a> to see the Top 500 addresses.</span>
                <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endif %}
            </div>
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7">Rank</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7">Address</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Balance</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder text-center opacity-7 ps-2">Comment</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for row in shimmer_richtlist %}
                    <tr>
                      <td>
                        <p class="text-sm font-weight-bold text-center mb-0">{{ forloop.counter }}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-center mb-0"><a href="https://explorer.shimmer.network/shimmer/addr/{{ row.address}}" target="_blank">{{ row.address }}</a></p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.balance }}</p>
                      </td>
                      <td>
                        <p class="text-sm font-weight-bold text-end mb-0">{{ row.comment }}</p>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
        </div>
      </div>
    </div>
  </div>
    {% endblock content %}
</html>

versutus/community/templates/opportunities.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block content %}
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Opportunities</h6>
              </div>
              <h7 class="text-capitalize ps-3">Total Opportunities: {{ count }}</h7>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Title</th>
                      <th id="category-header" class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Category</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Link</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for opportunity in opportunities %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div class="d-flex flex-column justify-content-center">
                            <p class="text-sm font-weight-bold text-end mb-0">{{ opportunity.name }}</p>
                          </div>
                        </div>
                      </td>
                      <td>
                        <p class="text-center text-xs font-weight-bold mb-0">{{ opportunity.category }}</p>
                      </td>
                      <td>
                        <p class="text-center text-xs font-weight-bold mb-0"><a href="https://discord.com/channels/397872799483428865/{{ opportunity.thread_id }}" target="_blank">View it on Discord</a></p>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <p class="text-sm font-weight-bold text-end mb-0">Updates every 12h</p>
        </div>
      </div>
    </div>
  </div>
    {% endblock content %}

versutus/community/templates/shimmerians.html
<!--
=========================================================
* Material Dashboard 2 - v3.0.4
=========================================================

* Product Page: https://www.creative-tim.com/product/material-dashboard
* Copyright 2022 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

{% block content %}
    <div class="container-fluid py-4">
      <div class="row">
        <div class="col-12">
          <div class="card my-4">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
                <h6 class="text-white text-capitalize ps-3">Shimmerians Leaderboard</h6>
              </div>
              <h7 class="text-capitalize ps-3">Total users: {{ total_users }}</h7>
            </div>
            {% if current_page > 1 %}
            <a href="?page={{ current_page|add:'-1' }}">Previous</a>
            {% endif %}

            {% if current_page < total_pages %}
            <a href="?page={{ current_page|add:'1' }}">Next</a>
            {% endif %}
            <div class="card-body px-0 pb-2">
              <div class="table-responsive p-0">
                <table class="table align-items-center justify-content-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">User</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Number of Quests</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">XPs</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
                          <div>
                            <p class="avatar avatar-sm me-3 border-radius-lg"><img src="{{ user.avatar }}" alt="{{ user.name }}'s avatar"></p>
                          </div>
                          <div class="d-flex flex-column justify-content-center">
                            <p class="text-sm font-weight-bold text-end mb-0">{{ user.name }}</p>
                          </div>
                        </div>
                      </td>
                      <td>
                        <p class="text-center text-xs font-weight-bold mb-0">{{ user.numberOfQuests }}</p>
                      </td>
                      <td>
                        <p class="text-center text-xs font-weight-bold mb-0">{{ user.xp }}</p>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    {% endblock content %}