config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("versutus.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

# Tangle URLS

urlpatterns += [
    path("tangle/", include("versutus.tangle.urls", namespace="tangle")),
    path("community/", include("versutus.community.urls", namespace="community")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

versutus/community/urls.py
from django.urls import path

from versutus.community.views import (
    communities_view,
    opportunities_view,
    shimmerians_view,
)

app_name = "crew3"

urlpatterns = [
    path("communities/", view=communities_view, name="communities"),
    path("communities/shimmerians/", view=shimmerians_view, name="shimmerians"),
    path("opportunities/", view=opportunities_view, name="opportunities"),
]

versutus/tangle/urls.py
from django.urls import path

from versutus.tangle.views import (
    crew3_tools_view,
    iota,
    shimmer,
    smr_address_view,
    tools_view,
)

app_name = "tangle"

urlpatterns = [
    path("iota/", view=iota, name="iota"),
    path("shimmer/", view=shimmer, name="shimmer"),
    path("tools/", view=tools_view, name="tools"),
    path("tools/crew3_smr/", view=crew3_tools_view, name="crew3_tools"),
    path("tools/smr_address/", view=smr_address_view, name="smr_address"),
]

versutus/users/urls.py
from django.urls import path

from versutus.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

versutus/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Versutus.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

versutus/tangle/forms.py
from django import forms


class SmrAddressForm(forms.Form):
    address = forms.CharField(
        max_length=64,
        widget=forms.TextInput(
            attrs={"maxlength": 64, "placeholder": "Enter SMR address"}
        ),
        required=True,
    )

versutus/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

versutus/community/views.py
import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from versutus.tangle.models import EcosystemOpportunities

User = get_user_model()


def get_crew3_api_data(subdomain, x_api_key, page_number):
    api_url = (
        f"https://api.crew3.xyz/communities/{subdomain}/leaderboard?page={page_number}"
    )
    headers = {"x-api-key": x_api_key}
    response = requests.get(api_url, headers=headers)
    return response.json()


def opportunities_view(request):
    # Retrieve all non-archived opportunities from the database
    opportunities = EcosystemOpportunities.objects.filter(archived=False)

    # Count the number of opportunities
    count = opportunities.count()

    # Pass the opportunities and count to the template context
    context = {
        "opportunities": opportunities,
        "count": count,
    }

    return render(request, "opportunities.html", context)


@login_required
def shimmerians_view(request):
    subdomain = "shimmerians"
    x_api_key = "72812apRGCSGJsgI99NIoAzcAeF"

    # Retrieve the page number from the request query string
    page_number = int(request.GET.get("page", 1))
    users = get_crew3_api_data(subdomain, x_api_key, page_number)

    for entry in users["leaderboard"]:
        if entry.get("avatar"):
            avatar_url = entry["avatar"]
            if avatar_url.startswith("https://cdn.discordapp.com/"):
                entry["avatar"] = avatar_url
            elif avatar_url.startswith("public/"):
                entry["avatar"] = (
                    "https://crew3-production.s3.eu-west-3.amazonaws.com/public/"
                    + avatar_url[7:]
                )
            else:
                entry["avatar"] = "https://crew3.xyz" + avatar_url
    # Add the total number of users and total pages to the context dictionary
    total_users = users["totalUsers"]
    total_pages = users["totalPages"]
    context = {
        "users": users["leaderboard"],
        "total_users": total_users,
        "total_pages": total_pages,
        "current_page": page_number,
    }
    return render(request, "shimmerians.html", context=context)


class Communities(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "leaderboard.html"


communities_view = Communities.as_view()

versutus/tangle/views.py
import csv
import logging

import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import render
from django.views.generic import TemplateView
from iota_client import (
    IotaClient as ShimmerClient,  # Imported as ShimmerClient to prevent confusion
)

from versutus.tangle.forms import SmrAddressForm
from versutus.tangle.models import (
    IotaDistribution,
    IotaTopAddress,
    ShimmerDistribution,
    ShimmerTopAddress,
)

logger = logging.getLogger(__name__)

User = get_user_model()


def is_user_in_nft_manager_group(user):
    try:
        nft_manager_group = Group.objects.get(name="NFT Managers")
    except Group.DoesNotExist:
        return False

    return nft_manager_group in user.groups.all()


def get_shimmer_richlist_from_chronicle_api(richlist_results):
    api_url = f"https://chronicle.shimmer.network/api/explorer/v2/ledger/richest-addresses?top={richlist_results}"
    response = requests.get(api_url)
    return response.json()


def iota(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    context = {
        "iota_distribution": IotaDistribution.objects.all(),
        "iota_richtlist": IotaTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
    }
    return render(request, "iota.html", context=context)


def shimmer(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    chronicle_api_richlist = get_shimmer_richlist_from_chronicle_api(richlist_results)
    for chronicle_api_entry in chronicle_api_richlist["top"]:
        shimmer_api_address = chronicle_api_entry["address"]
        shimmer_api_balance = chronicle_api_entry["balance"]
    shimmer_api_ledger_index = chronicle_api_richlist["ledgerIndex"]

    context = {
        "shimmer_distribution": ShimmerDistribution.objects.all(),
        "shimmer_richtlist": ShimmerTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
        "shimmer_api_ledger_index": shimmer_api_ledger_index,
        "shimmer_api_address": shimmer_api_address,
        "shimmer_api_balance": shimmer_api_balance,
    }
    return render(request, "shimmer.html", context=context)


def verify_content(csv_content):
    invalid_rows = []
    csv_reader = csv.reader(csv_content.splitlines())
    headers = next(csv_reader)
    if "answer" not in headers:
        invalid_rows.append((" ", "INVALID CSV FILE", " "))
        return invalid_rows

    address_index = headers.index("answer")
    if "Name" in headers:
        name_index = headers.index("Name")
    else:
        return invalid_rows
    for i, row in enumerate(csv_reader):
        logger.debug(row)
        if not verify_shimmer_address(row[address_index]):
            invalid_rows.append((row[name_index], row[address_index], i + 2))
    return invalid_rows


def verify_shimmer_address(address):
    logger.debug(f"Verifying address: {address}")
    shimmer_client = ShimmerClient()
    return shimmer_client.is_address_valid(address)


class Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "tools.html"


tools_view = Tools.as_view()


class Crew3Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "crew3_tools.html"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            csv_file = request.FILES["file"]
            csv_content = csv_file.read().decode("utf-8")
            invalid_rows = verify_content(csv_content)
            if invalid_rows:
                context = {
                    "invalid_rows": invalid_rows,
                }
                return render(request, "csv_verify.html", context=context)
            else:
                return render(request, "csv_success.html")
        return render(request, "csv_upload.html")


crew3_tools_view = Crew3Tools.as_view()


class ShimmerAddress(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "smr_address.html"
    form_class = SmrAddressForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        return self.render_to_response({"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            address = form.cleaned_data.get("address")
            if verify_shimmer_address(address):
                context = {"address": address}
                if address.startswith("rms1"):
                    context["testnet"] = True
                # Address is valid, do something
                return render(request, "smr_address_success.html", context=context)
            else:
                form.add_error("address", "Invalid address")
                context = {"address": address}
                return render(request, "smr_address_verify.html", context=context)
        return self.render_to_response({"form": form})


smr_address_view = ShimmerAddress.as_view()

versutus/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

versutus/users/views.py
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_user_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        social_account = SocialAccount.objects.filter(user=user).first()
        user_uid = social_account.uid
        print(f"user_uid: {user_uid}")
        # user_guilds = get_user_guilds(user_id=user_uid)
        # print(f"user_guilds: {user_guilds}")
        # system_guilds = get_system_guilds()

        # setup_status = False
        # guilds_setup_status = []
        # for user_guild in user_guilds:
        #     if str(user_guild.id) in str(system_guilds):
        #         try:
        #             setup_status = get_user_setup_status(user_id=user_id, guild_id=user_guild.id)
        #             if setup_status:
        #              guilds_setup_status.append({"id": user_guild.id, "guild_name": \
        #       user_guild.name, "icon": user_guild.icon, "setup_status": setup_status})
        #         except:
        #             continue

        # available_guilds = [{"id": guild["id"], "name": guild["guild_name"], \
        # "icon": guild["icon"]} for guild in guilds_setup_status if guild.get("setup_status", True)]
        # number_of_available_guilds = len(available_guilds)
        if social_account:
            context["social_account"] = social_account
        # Add new context to existing context
        context["user_uid"] = user_uid
        # context["user_guilds"] = user_guilds
        # context["number_of_available_guilds"] : number_of_available_guilds
        print(f"context: {context}")
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

versutus/templates/base copy.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
<link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">

<title>
  Versutus
</title>

<!--     Fonts and icons     -->
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

<!-- Nucleo Icons -->
<link href="{% static 'assets/css/nucleo-icons.css' %}" rel="stylesheet" />
<link href="{% static 'assets/css/nucleo-svg.css' %}" rel="stylesheet" />

<!-- Font Awesome Icons -->
<link rel="stylesheet" href="{% static 'fork-awesome/css/fork-awesome.min.css' %}">

<!-- Material Icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">

<!-- CSS Files -->
<link id="pagestyle" href="{% static 'assets/css/material-dashboard.css' %}?v=3.0.4" rel="stylesheet" />
</head>
<body class="g-sidenav-show  bg-gray-100">

{% block navbar %}

<main class="main-content border-radius-lg ">

   <!-- Navbar -->
   <nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl" id="navbarBlur" data-scroll="true">
    <div class="container-fluid py-1 px-3">
      <nav aria-label="home icon">
        <a href="/" class="nav-link text-body font-weight-bold px-0">
          <i class="fa fa-rocket me-sm-1"></i>
          <span class="d-sm-inline d-none">Versutus</span>
        </a>
      </nav>
      <div class="collapse navbar-collapse mt-sm-0 mt-2 me-md-0 me-sm-4" id="navbar">
        <div class="ms-md-auto pe-md-3 d-flex align-items-center">
        </div>
        <ul class="navbar-nav justify-content-end">
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'tangle:iota' %}" class="nav-link text-body font-weight-bold px-2">
              <span class="d-sm-inline d-none">🌀 IOTA</span>
            </a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'tangle:shimmer' %}" class="nav-link text-body font-weight-bold px-2">
              <span class="d-sm-inline d-none">✨ Shimmer</span>
            </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item d-flex align-items-center">
            <a href="{% url 'community:communities' %}" class="nav-link text-body font-weight-bold px-2" >
              <i class="fa fa-users me-sm-1"></i>
              <span class="d-sm-inline d-none">Crew3</span>
            </a>
          </li>
          {% endif %}
          {% if request.user.is_authenticated %}
          <li class="nav-item d-flex align-items-center">
            {# URL provided by django-allauth/account/urls.py #}
            <a href="{% url 'users:detail' request.user.username  %}" class="nav-link text-body font-weight-bold px-2" >
              <i class="fa fa-user me-sm-1"></i>
              <span class="d-sm-inline d-none">{% translate "My Profile" %}</span>
            </a>
          </li>
          <li class="nav-item d-flex align-items-center">
            {# URL provided by django-allauth/account/urls.py #}
            <a href="{% url 'account_logout' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-sign-out me-sm-1"></i>
              <span class="d-sm-inline d-none">{% translate "Sign Out" %}</span>
            </a>
          </li>
          {% else %}
          <li class="nav-item d-flex align-items-center">
            {# URL provided by django-allauth/account/urls.py #}
            <a id="log-in-link" href="{% url 'account_login' %}" class="nav-link text-body font-weight-bold px-0">
              <i class="fa fa-sign-in me-sm-1"></i>
              <span class="d-sm-inline d-none">{% translate "Sign In" %}
              </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- End Navbar -->

{% endblock navbar %}
<div class="alert alert-warning alert-dismissible text-white align-middle align-items-center" role="alert">
  <span class="text-sm">🚧 WORK IN PROGRESS 🚧. This site is pre-alpha status. Use at your own risk.</span>
  <!-- <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button> -->
</div>

{% block content %}
{% endblock content %}


<!-- Start footer -->
<footer class="footer py-4  ">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-lg-6 mb-lg-0 mb-4">
        <div class="copyright text-center text-sm text-muted text-lg-start">
          © <script>
            document.write(new Date().getFullYear())
          </script>,
          made with <i class="fa fa-heart"></i> by
          <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
          for a better web.
        </div>
        <div class="copyright text-center text-sm text-muted text-lg-start">
          Built on <a href="https://www.djangoproject.com/"class="font-weight-bold" target="_blank">Django</a> with <a href="https://github.com/cookiecutter/cookiecutter-django"class="font-weight-bold" target="_blank">Cookiecutter Django</a>
        </div>
      </div>
      <div class="col-lg-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://twitter.com/naerd_tech" class="nav-link text-muted" target="_blank"><i class="fa fa-twitter"></i></a>
          </li>
          <li class="nav-item">
            <a href="https://github.com/antonionardella" class="nav-link text-muted" target="_blank"><i class="fa fa-github"></i></a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">Theme license</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
</div>
</main>

   <!-- Core JS Files   -->
<script src="{% static 'assets/js/core/popper.min.js' %}" ></script>
<script src="{% static 'assets/js/core/bootstrap.min.js' %}" ></script>
<script src="{% static 'assets/js/plugins/perfect-scrollbar.min.js' %}" ></script>
<script src="{% static 'assets/js/plugins/smooth-scrollbar.min.js' %}" ></script>
<script>
  var win = navigator.platform.indexOf('Win') > -1;
  if (win && document.querySelector('#sidenav-scrollbar')) {
    var options = {
      damping: '0.5'
    }
    Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
  }
</script>

<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
<script src="{% static 'assets/js/material-dashboard.min.js' %}?v=3.0.4"></script>
</body>

</html>