config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("versutus.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

# Tangle URLS

urlpatterns += [
    path("tangle/", include("versutus.tangle.urls", namespace="tangle")),
    path("community/", include("versutus.community.urls", namespace="community")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

versutus/community/urls.py
from django.urls import path

from versutus.community.views import (
    communities_view,
    opportunities_view,
    shimmerians_view,
)

app_name = "crew3"

urlpatterns = [
    path("communities/", view=communities_view, name="communities"),
    path("communities/shimmerians/", view=shimmerians_view, name="shimmerians"),
    path("opportunities/", view=opportunities_view, name="opportunities"),
]

versutus/tangle/urls.py
from django.urls import path

from versutus.tangle.views import (
    crew3_tools_view,
    iota,
    shimmer,
    smr_address_view,
    tools_view,
)

app_name = "tangle"

urlpatterns = [
    path("iota/", view=iota, name="iota"),
    path("shimmer/", view=shimmer, name="shimmer"),
    path("tools/", view=tools_view, name="tools"),
    path("tools/crew3_smr/", view=crew3_tools_view, name="crew3_tools"),
    path("tools/smr_address/", view=smr_address_view, name="smr_address"),
]

versutus/users/urls.py
from django.urls import path

from versutus.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

versutus/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Versutus.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

versutus/tangle/forms.py
from django import forms


class SmrAddressForm(forms.Form):
    address = forms.CharField(
        max_length=64,
        widget=forms.TextInput(
            attrs={"maxlength": 64, "placeholder": "Enter SMR address"}
        ),
        required=True,
    )

versutus/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

versutus/community/views.py
import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import TemplateView

from versutus.tangle.models import EcosystemOpportunities

User = get_user_model()


def get_crew3_api_data(subdomain, x_api_key, page_number):
    api_url = (
        f"https://api.crew3.xyz/communities/{subdomain}/leaderboard?page={page_number}"
    )
    headers = {"x-api-key": x_api_key}
    response = requests.get(api_url, headers=headers)
    return response.json()


def opportunities_view(request):
    # Retrieve all non-archived opportunities from the database
    opportunities = EcosystemOpportunities.objects.filter(archived=False)

    # Count the number of opportunities
    count = opportunities.count()

    # Pass the opportunities and count to the template context
    context = {
        "opportunities": opportunities,
        "count": count,
    }

    return render(request, "opportunities.html", context)


@login_required
def shimmerians_view(request):
    subdomain = "shimmerians"
    x_api_key = "72812apRGCSGJsgI99NIoAzcAeF"

    # Retrieve the page number from the request query string
    page_number = int(request.GET.get("page", 1))
    users = get_crew3_api_data(subdomain, x_api_key, page_number)

    for entry in users["leaderboard"]:
        if entry.get("avatar"):
            avatar_url = entry["avatar"]
            if avatar_url.startswith("https://cdn.discordapp.com/"):
                entry["avatar"] = avatar_url
            elif avatar_url.startswith("public/"):
                entry["avatar"] = (
                    "https://crew3-production.s3.eu-west-3.amazonaws.com/public/"
                    + avatar_url[7:]
                )
            else:
                entry["avatar"] = "https://crew3.xyz" + avatar_url
    # Add the total number of users and total pages to the context dictionary
    total_users = users["totalUsers"]
    total_pages = users["totalPages"]
    context = {
        "users": users["leaderboard"],
        "total_users": total_users,
        "total_pages": total_pages,
        "current_page": page_number,
    }
    return render(request, "shimmerians.html", context=context)


class Communities(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "leaderboard.html"


communities_view = Communities.as_view()

versutus/tangle/views.py
import csv
import logging

import requests
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.shortcuts import render
from django.views.generic import TemplateView
from iota_client import (
    IotaClient as ShimmerClient,  # Imported as ShimmerClient to prevent confusion
)

from versutus.tangle.forms import SmrAddressForm
from versutus.tangle.models import (
    IotaDistribution,
    IotaTopAddress,
    ShimmerDistribution,
    ShimmerTopAddress,
)

logger = logging.getLogger(__name__)

User = get_user_model()


def is_user_in_nft_manager_group(user):
    try:
        nft_manager_group = Group.objects.get(name="NFT Managers")
    except Group.DoesNotExist:
        return False

    return nft_manager_group in user.groups.all()


def get_shimmer_richlist_from_chronicle_api(richlist_results):
    api_url = f"https://chronicle.shimmer.network/api/explorer/v2/ledger/richest-addresses?top={richlist_results}"
    response = requests.get(api_url)
    return response.json()


def iota(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    context = {
        "iota_distribution": IotaDistribution.objects.all(),
        "iota_richtlist": IotaTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
    }
    return render(request, "iota.html", context=context)


def shimmer(request):
    if request.user.is_authenticated:
        richlist_results = 500
    else:
        richlist_results = 20

    chronicle_api_richlist = get_shimmer_richlist_from_chronicle_api(richlist_results)
    for chronicle_api_entry in chronicle_api_richlist["top"]:
        shimmer_api_address = chronicle_api_entry["address"]
        shimmer_api_balance = chronicle_api_entry["balance"]
    shimmer_api_ledger_index = chronicle_api_richlist["ledgerIndex"]

    context = {
        "shimmer_distribution": ShimmerDistribution.objects.all(),
        "shimmer_richtlist": ShimmerTopAddress.objects.all()[:richlist_results],
        "richlist_results": richlist_results,
        "shimmer_api_ledger_index": shimmer_api_ledger_index,
        "shimmer_api_address": shimmer_api_address,
        "shimmer_api_balance": shimmer_api_balance,
    }
    return render(request, "shimmer.html", context=context)


def verify_content(csv_content):
    invalid_rows = []
    csv_reader = csv.reader(csv_content.splitlines())
    headers = next(csv_reader)
    if "answer" not in headers:
        invalid_rows.append((" ", "INVALID CSV FILE", " "))
        return invalid_rows

    address_index = headers.index("answer")
    if "Name" in headers:
        name_index = headers.index("Name")
    else:
        return invalid_rows
    for i, row in enumerate(csv_reader):
        logger.debug(row)
        if not verify_shimmer_address(row[address_index]):
            invalid_rows.append((row[name_index], row[address_index], i + 2))
    return invalid_rows


def verify_shimmer_address(address):
    logger.debug(f"Verifying address: {address}")
    shimmer_client = ShimmerClient()
    return shimmer_client.is_address_valid(address)


class Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "tools.html"


tools_view = Tools.as_view()


class Crew3Tools(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "crew3_tools.html"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            csv_file = request.FILES["file"]
            csv_content = csv_file.read().decode("utf-8")
            invalid_rows = verify_content(csv_content)
            if invalid_rows:
                context = {
                    "invalid_rows": invalid_rows,
                }
                return render(request, "csv_verify.html", context=context)
            else:
                return render(request, "csv_success.html")
        return render(request, "csv_upload.html")


crew3_tools_view = Crew3Tools.as_view()


class ShimmerAddress(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "smr_address.html"
    form_class = SmrAddressForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        return self.render_to_response({"form": form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            address = form.cleaned_data.get("address")
            if verify_shimmer_address(address):
                context = {"address": address}
                if address.startswith("rms1"):
                    context["testnet"] = True
                # Address is valid, do something
                return render(request, "smr_address_success.html", context=context)
            else:
                form.add_error("address", "Invalid address")
                context = {"address": address}
                return render(request, "smr_address_verify.html", context=context)
        return self.render_to_response({"form": form})


smr_address_view = ShimmerAddress.as_view()

versutus/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

versutus/users/views.py
from allauth.socialaccount.models import SocialAccount
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_user_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        social_account = SocialAccount.objects.filter(user=user).first()
        user_uid = social_account.uid
        print(f"user_uid: {user_uid}")
        # user_guilds = get_user_guilds(user_id=user_uid)
        # print(f"user_guilds: {user_guilds}")
        # system_guilds = get_system_guilds()

        # setup_status = False
        # guilds_setup_status = []
        # for user_guild in user_guilds:
        #     if str(user_guild.id) in str(system_guilds):
        #         try:
        #             setup_status = get_user_setup_status(user_id=user_id, guild_id=user_guild.id)
        #             if setup_status:
        #              guilds_setup_status.append({"id": user_guild.id, "guild_name": \
        #       user_guild.name, "icon": user_guild.icon, "setup_status": setup_status})
        #         except:
        #             continue

        # available_guilds = [{"id": guild["id"], "name": guild["guild_name"], \
        # "icon": guild["icon"]} for guild in guilds_setup_status if guild.get("setup_status", True)]
        # number_of_available_guilds = len(available_guilds)
        if social_account:
            context["social_account"] = social_account
        # Add new context to existing context
        context["user_uid"] = user_uid
        # context["user_guilds"] = user_guilds
        # context["number_of_available_guilds"] : number_of_available_guilds
        print(f"context: {context}")
        return context


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

versutus/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
  <div class="container-fluid px-2 px-md-4">
    <div class="card card-body mx-3 mx-md-1 mt-n1">
      <div class="row gx-4 mb-2">
        <div class="col-auto">
          <div class="avatar avatar-xl position-relative">
            <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
          </div>
        </div>
        <div class="col-auto my-auto">
          <div class="h-100">
            <h5 class="mb-1">
              {{ object.username }}#{{ object.socialaccount_set.all.0.extra_data.discriminator }}
            </h5>
            <p class="mb-0 font-weight-normal text-sm">
              Premium type: {% if object.socialaccount_set.all.0.extra_data.premium_type == 1 %}Nitro Classic{% elif object.socialaccount_set.all.0.extra_data.premium_type == 2 %}Nitro{% elif object.socialaccount_set.all.0.extra_data.premium_type == 3 %}Nitro Basic{% else %}None{% endif %}
            </p>
          </div>
        </div>
        <!-- {{ user }} -->
        {% if object == request.user %}
        <div class="my-sm-auto ms-sm-auto me-sm-0 mx-auto mt-2">
          <div class="nav-wrapper position-relative end-0">
            <!-- <ul class="nav nav-tabs" id="myTab" role="tablist"> -->
            <ul class="nav nav-pills nav-fill p-1" id="myTab" role="tablist">
              <li class="nav-item" role="presentation">
                <a class="nav-link mb-0 px-0 py-0 active"  id="tools-tab" data-bs-toggle="tab" data-bs-target="#tools-tab-pane" type="button" role="tab" aria-controls="contact-tab-pane" aria-selected="false">
                  <i class="material-icons text-lg position-relative">handyman</i>
                  <span class="ms-1">Tools</span>
                </a>
              </li>
              <li class="nav-item" role="presentation">
                <a class="nav-link mb-0 px-0 py-0" id="servers-tab" data-bs-toggle="tab" data-bs-target="#servers-tab-pane" type="button" role="tab" aria-controls="servers-tab-pane" aria-selected="true">
                  <i class="material-icons text-lg position-relative">storage</i>
                  <span class="ms-1">Servers</span>
                </a>
              </li>
              <li class="nav-item" role="presentation">
                <a class="nav-link  mb-0 px-0 py-0" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">
                  <i class="material-icons text-lg position-relative">settings</i>
                  <span class="ms-1">Settings</span>
                </a>
              </li>
            </ul>
            <div class="tab-content" id="myTabContent">
              <div class="tab-pane fade" id="servers-tab-pane" role="tabpanel" aria-labelledby="servers-tab" tabindex="0">
                <div class="container-fluid px-2 px-md-4">
                  <div class="card card-body mx-0 mx-md-0">
                    <div class="col-12 mt-4">
                      <div class="row">
                        <div class="row">
                        {% if setup_status %}
                          <h6 class="mb-1">
                            {% if number_of_available_guilds == 0 %}
                            You are not in an eligible server
                            {% elif number_of_available_guilds == 1 %}
                            You are in 1 server
                            {% else %}
                            You are in: {{number_of_available_guilds}} servers
                            {% endif %}
                          </h6>
                          <p class="text-sm">
                            {% if number_of_available_guilds == 69 %}
                            Nice!
                            {% endif %}
                          </p>
                        </div>
                        <div class="row">
                          {% for guild in available_guilds %}
                          <div class="col-xl-3 col-md-3 mb-xl-0 mb-4">
                            <div class="card card-blog card-plain">
                              <div class="card-header p-0 mt-n4 mx-3">
                                <!-- <a class="d-block shadow-xl border-radius-xl"> -->
                                <a href="{% url 'server' guild.id %}">
                                  {% if guild.icon is None %}
                                    <img src="https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6918e57475a843f59f_icon_clyde_black_RGB.svg" alt="img-blur-shadow" class="guild-icon img-fluid shadow border-radius-xl rounded-circle">
                                  {% else %}
                                    <img src="https://cdn.discordapp.com/icons/{{guild.id}}/{{guild.icon}}.webp" alt="img-blur-shadow" class="guild-icon img-fluid shadow border-radius-xl rounded-circle">
                                  {% endif %}
                              </div>
                              <div class="card-body p-3">
                                <!-- <p class="mb-0 text-sm">{{guild.name}}</p> -->
                                  <h5 class="text-left">
                                    {{guild.name}}
                                  </h5>
                                </a>
                              </div>
                            </div>
                          </div>
                          {% endfor %}
                        </div>
                        {% else %}
                          <h2>
                            The profile is not set up on any server.
                          </h2>
                          <p class="mb-0 text-sm">
                            Please join a server served by Versutus and set the profile up using the command <code>/usersetup</code>
                          </p>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              </div>
              <div class="tab-pane fade show active" id="tools-tab-pane" role="tabpanel" aria-labelledby="tools-tab" tabindex="0">
                <div class="container-fluid px-2 px-md-4">
                  <div class="card card-body mx-3 mx-md-4">
                    <div class="col-12 mt-4">
                      <div class="row">
                        <div class="card-body px-0 pb-2">
                          <div class="table-responsive p-0">
                            <table class="table align-items-center mb-0">
                              <thead>
                                <tr>
                                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Tool</th>
                                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Function</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td>
                                    <div class="d-flex px-2 py-1">
                                      <a href="{% url 'tangle:tools' %}">
                                      <div>
                                        <img src="https://cdn.discordapp.com/avatars/1062724060557086772/054e1e28f739c05ab29ca6178698e6de.png" class="avatar avatar-sm me-3 border-radius-lg" alt="user2">
                                      </div>
                                      <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Versutus Shimmer Tools</h6>
                                      </a>
                                        <p class="text-xs text-secondary mb-0">Custom built tools</p>
                                      </div>
                                    </div>
                                  </td>
                                  <td>
                                    <p class="text-xs font-weight-bold mb-0">Address checker, Crew3 tools, etc..</p>
                                    <p class="text-xs text-secondary mb-0">in progress</p>
                                  </td>
                                </tr>
                                <tr>
                                  <td>
                                    <div class="d-flex px-2 py-1">
                                      <a href="https://explorer.shimmer.network/shimmer" target="_blank">
                                        <div>
                                          <img src="https://shimmer.network/assets/logo.svg" class="avatar avatar-sm me-3 border-radius-lg" alt="Shimmer logo">
                                        </div>
                                        <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">Shimmer Explorer</h6>
                                      </a>
                                        <p class="text-xs text-secondary mb-0"><a href="https://explorer.shimmer.network/shimmer" target="_blank">https://explorer.shimmer.network/shimmer</a></p>
                                      </div>
                                    </div>
                                  </td>
                                  <td>
                                    <p class="text-xs font-weight-bold mb-0">Shimmer Tangle Explorer</p>
                                    <p class="text-xs font-weight-bold mb-0"></p>
                                    <p class="text-xs text-secondary mb-0"></p>
                                  </td>
                                </tr>
                                <tr>
                                  <td>
                                    <div class="d-flex px-2 py-1">
                                      <div>
                                        <!-- <img src="" class="avatar avatar-sm me-3 border-radius-lg" alt="user2"> -->
                                        <i class="fa fa-ban"></i>
                                      </div>
                                      <div class="d-flex flex-column justify-content-center">
                                        <h6 class="mb-0 text-sm">WIP</h6>
                                        <p class="text-xs text-secondary mb-0">WIP</p>
                                      </div>
                                    </div>
                                  </td>
                                  <td>
                                    <p class="text-xs font-weight-bold mb-0">Work</p>
                                    <p class="text-xs text-secondary mb-0">in progress</p>
                                  </td>
                                </tr>
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="tab-pane fade" id="settings-tab-pane" role="tabpanel" aria-labelledby="settings-tab" tabindex="0">
                <div class="container-fluid px-2 px-md-4">
                  <div class="card card-body mx-3 mx-md-4">
                    <div class="col-12 mt-4">
                      <div class="row">

                        SETTINGS

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


{% endif %}
</div>
{% endblock content %}

versutus/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}